version: '2'
services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: bla
      POSTGRES_PASSWORD: bla
      POSTGRES_DB: criticalmaps
    ports:
      - "5432:5432"
    expose:
        - "5432"
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: production
      DEBUG: "*"
      POSTGRES_USER: bla
      POSTGRES_PASSWORD: bla
      POSTGRES_PORT: 5432
      POSTGRES_DB: criticalmaps
      POSTGRES_HOST: db
      DATABASE_URL: postgres://bla:bla@db/criticalmaps
    links:
      - db
    restart: always
